feat: add av1 support via svt as well

diff --git a/.devpod/Dockerfile b/.devpod/Dockerfile
--- a/.devpod/Dockerfile
+++ b/.devpod/Dockerfile
@@ -15,6 +15,9 @@ RUN apt update && apt install -y git procps curl wget \
 # Try to install libfdk-aac-dev, but don't fail if it's not available
 RUN apt update && apt install -y libfdk-aac-dev || echo "libfdk-aac-dev not available, continuing without it"
 
+# Install build dependencies for SVT-AV1
+RUN apt update && apt install -y cmake build-essential yasm
+
 # Install Rust using rustup and install rav1e
 RUN apt update && apt install -y curl build-essential
 RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
@@ -22,8 +25,24 @@ ENV PATH="/root/.cargo/bin:${PATH}"
 RUN rustup default stable
 RUN cargo install rav1e
 
+# Install SVT-AV1
+RUN cd /tmp && \
+    git clone --depth 1 https://gitlab.com/AOMediaCodec/SVT-AV1.git && \
+    cd SVT-AV1 && \
+    mkdir build && \
+    cd build && \
+    cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && \
+    make -j$(nproc) && \
+    make install && \
+    ldconfig && \
+    cd / && \
+    rm -rf /tmp/SVT-AV1
+
 # Make rav1e globally available
 RUN cp /root/.cargo/bin/rav1e /usr/local/bin/
+
+# Make SVT-AV1 binary available in PATH
+RUN cp /usr/local/bin/SvtAv1EncApp /usr/bin/ || echo "SvtAv1EncApp not found in /usr/local/bin"
 
 # Install pnpm
 RUN npm install -g pnpm
